---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-intelligent-service
  labels:
    app: crm-intelligent-service
  namespace: crm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crm-intelligent-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crm-intelligent-service
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: >-
            registry.cn-beijing.aliyuncs.com/bjczht/crm-intelligent-service:2.8.0-191015.2001-d9995f28
          imagePullPolicy: Always
          name: crm-intelligent-service
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
             - mountPath: /etc/hosts
               name: volume-hosts
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/hosts
            type: ''
          name: volume-hosts 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: crm-intelligent-service
  name: crm-intelligent-service
  namespace: crm
  resourceVersion: '1910'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: zxzhdn
      nodePort: 
      port: 30013
      protocol: TCP
      targetPort: 30013
  selector:
    app: crm-intelligent-service
  sessionAffinity: None
  type: NodePort
