---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-adapter
  labels:
    app: rocketmq-adapter
  namespace: crm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rocketmq-adapter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-adapter
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: >-
            registry.cn-beijing.aliyuncs.com/bjczht/rocketmq-adapter:2.0.0-190426.1653-1ca7cb91
          imagePullPolicy: Always
          name: rocketmq-adapter
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
             - mountPath: /etc/hosts
               name: volume-hosts
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/hosts
            type: ''
          name: volume-hosts 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: rocketmq-adapter
  name: rocketmq-adapter
  namespace: crm
  resourceVersion: '1910'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: zxzhdn
      nodePort: 
      port: 30012
      protocol: TCP
      targetPort: 30012
  selector:
    app: rocketmq-adapter
  sessionAffinity: None
  type: NodePort
