---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-provider
  labels:
    app: base-provider
  namespace: autosaas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: base-provider
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: base-provider
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: >-
            registry.cn-beijing.aliyuncs.com/bjczht/base-provider:2.8.0-191014.1548-92ec90db
          imagePullPolicy: Always
          name: base-provider
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
             - mountPath: /etc/hosts
               name: volume-hosts
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/hosts
            type: ''
          name: volume-hosts 

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: base-provider
  name: base-provider
  namespace: autosaas
  resourceVersion: '2019'
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
    - name: mjtifz
      nodePort: 32135
      port: 13001
      protocol: TCP
      targetPort: 13001
  selector:
    app: base-provider
  sessionAffinity: None
  type: NodePort
