---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-provider
  labels:
    app: dealer-provider
  namespace: autosaas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dealer-provider
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dealer-provider
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: >-
            registry.cn-beijing.aliyuncs.com/bjczht/dealer-provider:2.9.0-191029.1845-e4eab10e
          imagePullPolicy: Always
          name: dealer-provider
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
             - mountPath: /etc/hosts
               name: volume-hosts
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/hosts
            type: ''
          name: volume-hosts 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dealer-provider
  name: dealer-provider
  namespace: autosaas
  resourceVersion: '2072'
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
    - name: jhn6bg
      nodePort: 30483
      port: 14001
      protocol: TCP
      targetPort: 14001
  selector:
    app: dealer-provider
  sessionAffinity: None
  type: NodePort

