---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-gateway
  labels:
    app: partner-gateway
  namespace: autosaas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: partner-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: partner-gateway
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: >-
            registry.cn-beijing.aliyuncs.com/bjczht/partner-gateway:2.3.0-190723.1637-ddfc1c5b
          imagePullPolicy: Always
          name: partner-gateway
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
             - mountPath: /etc/hosts
               name: volume-hosts
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/hosts
            type: ''
          name: volume-hosts 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: partner-gateway
  name: partner-gateway
  namespace: autosaas
  resourceVersion: '1910'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: zxzhdn
      nodePort: 
      port: 21001
      protocol: TCP
      targetPort: 21001
  selector:
    app: partner-gateway
  sessionAffinity: None
  type: NodePort
