---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
  labels:
    app: xxl-job-admin
  namespace: autosaas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xxl-job-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: >-
            registry.cn-beijing.aliyuncs.com/bjczht/public-xxl-job-admin:2.0.2-190529-1814
          imagePullPolicy: Always
          name: xxl-job-admin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
             - mountPath: /etc/hosts
               name: volume-hosts
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/hosts
            type: ''
          name: volume-hosts 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: xxl-job-admin
  name: xxl-job-admin
  namespace: autosaas
  resourceVersion: '1910'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: zxzhdn
      nodePort: 
      port: 41101
      protocol: TCP
      targetPort: 41101
  selector:
    app: xxl-job-admin
  sessionAffinity: None
  type: NodePort
