version: '2'

services:
  bioportainer-panel:
    image: bioportainer/bioportainer-panel
    container_name: "bioportainer-panel"
    privileged: true
    stdin_open: true
    restart: always
    ports:
      - "9088:9000"
    networks:
      - bioportainer-local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/bioportainer_data:/data
      
  bioportainer-pipeline-runner:
    image: bioportainer/bioportainer-pipeline-runner
    container_name: "bioportainer-pipeline-runner"
    privileged: true
    stdin_open: true
    restart: always
    ports:
      - "5000:5000"
      - "7000:7000"
      - "8888:8888"
    networks:
      - bioportainer-local
    volumes:
      - ${PWD}/bioportainer_workdir:/root/.nextflow/assets
      
  bioportainer-watchtower:
    image: v2tec/watchtower
    stdin_open: true
    restart: always
    container_name: "bioportainer-watchtower"
    command: --cleanup portainer-base bioportainer-watchtower bioportainer-pipeline-runner
    networks:
      - bioportainer-local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bioportainer-local:
    driver: bridge

volumes:
    bioportainer_data:
    bioportainer_workdir:
